version: '3.7'
services:
    betternode:
        container_name: better-node
        build:
            context: .
            dockerfile: Dockerfiles/BetterNode.dockerfile
        network_mode: "host"
    producer1node:
        container_name: producer1-node
        build:
            context: .
            dockerfile: Dockerfiles/Producer1Node.dockerfile
        network_mode: "host"
    producer2node:
        container_name: producer2-node
        build: 
            context: .
            dockerfile: Dockerfiles/Producer2Node.dockerfile
        network_mode: "host"