version: '3.7'
services:
    betternode:
        container_name: better-node
        build:
            context: .
            dockerfile: Dockerfiles/BetterNode.dockerfile
        network_mode: "host"
    producernode:
        container_name: producer-node
        build:
            context: .
            dockerfile: Dockerfiles/ProducerNode.dockerfile
        network_mode: "host"
    consumernode:
        container_name: consumer-node
        build: 
            context: .
            dockerfile: Dockerfiles/ConsumerNode.dockerfile
        network_mode: "host"